12.office management/application/views/manager.py
from ..model import db
from flask import Blueprint, redirect,render_template,request,session, url_for
from bson.objectid import ObjectId

manager_blueprint = Blueprint('manager_blueprint', __name__,static_folder='static',template_folder='templates')


def console(inner):
    print("\n"*3)
    print(inner)
    print("\n"*3)
    
def return_manager(inner):
    return db['manager'].find_one( {"_id" :ObjectId(inner)} )
    
    
@manager_blueprint.route('/<string:_id>')
def manager(_id):
    return render_template('manager/index.html',manager=return_manager(_id))



    
@manager_blueprint.route('/employee/<string:_id>/<string:manager_id>')
def employee(_id,manager_id):
    
    employee = db['employee'].find_one({'_id':ObjectId(_id)})
    return render_template('manager/employee.html',data=employee,manager = return_manager(manager_id))  


@manager_blueprint.route('/update_manager/',methods=["POST"])
def update_employee():
    if request.method == 'POST':
        form = request.form
        
        manager =  db['manager'].find_one( {"_id" :ObjectId(form['manager_id'])} )
        amount = int(manager["amount"]) - 10
        arr  =  manager['salary_list']
        arr.append(ObjectId(form['employee_id']))
        db['manager'].find_one_and_update(
            {'_id':ObjectId(form['manager_id'])},
            {'$set':{'amount':amount,"salary_list":arr } })

        db['employee'].find_one_and_update(
            {'_id':ObjectId(form['employee_id'])},
            {'$set':{'salary':True ,"manager_name":manager['name'],"manager_id":manager['_id']} })
        
        
    return redirect(url_for('manager_blueprint.employee',_id=ObjectId(form['employee_id']),manager_id=manager["_id"]))




@manager_blueprint.route('/search_list',methods=['GET','POST'])
def search_list():
        if request.method == 'POST':
            form = request.form

        regex = {'$regex':  f'^{form["search"]}', '$options' : 'i'}
        documents = []
        
        for doc in db['employee'].find( {'name': regex} ):
            documents.append(doc)
        
        console(documents)
        
        return render_template('manager/search_list.html',data = {
            "search_list" : documents,
            "search_count" : len(documents)
        },manager=return_manager(form['manager_id']))


@manager_blueprint.route('/salary_list/<string:manager_id>')
def salary_list(manager_id):
    manager  = return_manager(manager_id)
    data = db['employee'].find({    '_id':  { "$in" :manager['salary_list']}      })
    return render_template("manager/salary_list.html",data=data,manager = manager)














@manager_blueprint.route('/bar_room/<string:manager_id>')
def bar_room(manager_id):
    manager  = return_manager(manager_id)

    data = db['employee'].find(
        {"manager_id":ObjectId(manager_id) , "attendance":False}
        )
        
    return render_template("manager/bar_room.html",data = data,manager=manager)

12.office management/application/templates/manager/bar_room.html
{%extends 'layout.html'%}
{%block content%}
{% include 'manager/navbar.html'%}

<div class="container text-center">
    <h1>Not attend</h1>
    <table class="table ">
        <thead>
            <tr>
                <th>Name</th>
                <th>Number</th>
                <th>Manager</th>
                <th>Area</th>
            </tr>
        </thead>
        <tbody>
            {%for employee in data%}
            <tr>
                <td scope="row">
                    <a href="/manager/employee/{{employee ._id}}/{{manager._id}}" class="btn">

                        {{employee['name']}}
                    </a>
                </td>
                <td scope="row">{{employee['number']}}</td>
                <td scope="row">{{employee['manager_name']}}</td>

                <td scope="row">
                    {%if  employee.area %}
                    <h5 class="text-danger" > Outsider </h5>
                    {% else %}
                    <span class="h5">{{employee['area']}}</span>
                    {%endif%}

                </td>
            </tr>
            {%endfor%}

        </tbody>

    </table>
    </div>


    {%endblock%}

12.office management/application/templates/manager/employee.html
{%extends 'layout.html'%} {%block content%} {% include 'manager/navbar.html'%}

<div class="container text-center P-3 ">
    <h2 class="">{{ data['name']}}

        <small>employee</small>
    </h2>

    
    <div class="d-flex justify-content-center">

        <ul class="list-group " style="width: 600px;">
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Number<span class="h5">{{data['number']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Voter Id<span class="h5">{{data['voter_id']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Father Name<span class="h5">{{data['father_name']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Date of birth<span class="h5">{{data['dob']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Address<span class="h5">{{data['address']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Polling Booth<span class="h5">{{data['polling_booth']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Area<span class="h5">{{data['area']}}</span></li>

        </ul>
    </div>


    {%if data['salary'] %}
    <button  class="btn btn-primary m-3" disabled>
        Salary given by {{data['manager_name']}} 
    </button>

    {%else%}
    <form action="{{url_for('manager_blueprint.update_employee')}}" method="post">
        
        <input type="text" id="element1" value="{{session.user._id}}" name="manager_id">
        <input type="text" id="element2" value="{{session.user.amount }}" name="manager_amount">
        <input type="text" id="element3" value="{{data['_id']}}" name="employee_id"> 
        <input type="submit" class="btn btn-primary m-3" value="salary"> 
        

    </form>



    {%endif%}

    <script>
        document.getElementById("element1").style.display = "none";
        document.getElementById("element2").style.display = "none";
        document.getElementById("element3").style.display = "none";
    </script>
</div>

{%endblock%}

12.office management/application/templates/manager/employee_list.html
{%extends 'layout.html'%} {%block content%} {% include 'manager/navbar.html'%}
<nav class="navbar m-1   members_attendance ">
    <div class="container-fluid">
        <div class="navbar ">
            <h3>Employee {{data['employee_count']}}</h3>
        </div>

        <div class="d-flex">
            <ul class="nav nav-pills nav-fill ">


            </ul>


        </div>
    </div>
</nav>

<div class="container">
    <table class="table table-hover">

        <thead>
            <tr>
                <th scope="col">Name</th>
            </tr>
        </thead>



        <tbody>
            {%for data in data['employee_list']%}
            <!-- <tr onclick="window.location='employee/{{data._id}}-{{session.user._di}}' "> -->
            <tr onclick="window.location='manager/'">
                <th scope="row">{{data['name']}}</th>
            </tr>
            {%endfor%}

        </tbody>


    </table>
</div>


{%endblock%}

12.office management/application/templates/manager/index.html
{%extends 'layout.html'%}
{%block content%}
{% include 'manager/navbar.html'%}

<div class="container text-center">
  <div class="card">
    <div class="card-header">
      <h1>{{manager['amount']}}</h1>
      <small>Balance amount</small>
    </div>
    <div class="card-body">
      <h3 class="card-title">{{manager['total_amount']}} <small>Total amount</small></h3>
      
      <p class="card-text">salary given <b> {{ (manager['salary_list'] | length)*10  }} </b>for <b> {{ manager['salary_list'] | length }} </b> employees </p>

      <form method="post" action="{{url_for('manager_blueprint.search_list')}}">
        
        <input class="form-control me-2" type="text" id="element6" value="" name="search" autocomplete="off">
        <input type="text" name="manager_id" id="element5" value="{{session.user._id}}">
        <button type="submit" class="btn btn-primary">Give salary </button>
      </form>

      <script>
        document.getElementById("element5").style.display = "none";
        document.getElementById("element6").style.display = "none";
    </script>

    </div>  
  </div>
</div>
{%endblock%}

12.office management/application/templates/manager/navbar.html
<nav class="navbar m-1   bg-light">
    <div class="container-fluid">
        <div class="navbar ">
            <a href="/manager/{{manager['_id']}}" class="btn">
                <h3> {{manager['name']}} / {{manager['amount']}} 
                    <small class="h5 text-muted"> -   {{session.type}}</small>
                </h3>
            </a>
        </div>



        <div class="d-flex">
            <ul class="nav nav-pills nav-fill  ">


                <li class="nav-item  m-2">
                    <!-- <a class=" btn btn-outline-primary active" aria-current="page" href="{{url_for('manager_blueprint.salary_list',manager_id= '{{session.type}}'  )}}">Salary given list -->
                    <a class=" btn btn-outline-primary active" aria-current="page" href="/manager/bar_room/{{manager['_id']}}">Bar Room
                </a>
                </li>

                <li class="nav-item  m-2">
                    <!-- <a class=" btn btn-outline-primary active" aria-current="page" href="{{url_for('manager_blueprint.salary_list',manager_id= '{{session.type}}'  )}}">Salary given list -->
                    <a class=" btn btn-outline-primary active" aria-current="page" href="/manager/salary_list/{{manager['_id']}}">Salary given list
                </a>
                </li>

                <li class="nav-item  m-2">
                    <form class="d-flex" method="post" action="{{url_for('manager_blueprint.search_list')}}">
                        <input class="form-control me-2" type="text" aria-label="Search" placeholder="Name" value="" name="search" autocomplete="off">
                        <input type="text" name="manager_id" id="element" value="{{session.user._id}}">
                        <button type="submit" class="btn btn-primary">Search </button>
                    </form>
                </li>

                <script>
                    document.getElementById("element").style.display = "none";
                </script>

            </ul>


        </div>
    </div>
</nav>

12.office management/application/templates/manager/salary_list.html
{%extends 'layout.html'%}
{%block content%} {% include 'manager/navbar.html'%}

<div class="container">
    <table class="table table-hover">
  
      <thead>
        <tr>
          <th scope="col">Name</th>
          
        <th> Voter id</th>
        <th> Father name</th>
        <th> Number</th>
        <th>Outsider</th>
        <th> Salary</th>
        <th> Manager_name</th>
        <th> Attendance</th>
        </tr>
      </thead>
  
  
  
      <tbody>
        {%for data in data%}
        <tr onclick="window.location='/manager/employee/{{data._id}}/{{manager._id}}' ">
          <th scope="row">{{data['name']}}</th>
          <td> {{data['voter_id']}} </td>
          <td> {{data['father_name']}} </td>
          <td> {{data['number']}} </td>
          <td> {{data['area']}} </td>
          <td> {{data['salary']}} </td>
          <td> {{data['manager_name']}} </td>
          <td> {{data['attendance']}} </td>
        </tr>
        {%endfor%}
  
      </tbody>
  
  
    </table>
  </div>
  

{%endblock%}

12.office management/application/templates/manager/search_list.html
{%extends 'layout.html'%}
{%block content%}
{% include 'manager/navbar.html'%}

<div class="container">
  <table class="table table-hover">

    <thead>
      <tr>
        <th scope="col">Name</th>

        <th> Voter id</th>
        <th> Father name</th>
        <th> Number</th>
        <th>Outsider</th>
        <th> Salary</th>
        <th> Manager_name</th>
        <th> Attendance</th>
        

      </tr>
    </thead>



    <tbody>
      {%for employee in data['search_list']%}
      <tr onclick="window.location='/manager/employee/{{employee._id}}/{{manager._id}}' ">
        <th scope="row">{{employee['name']}}</th>
        <td> {{employee['voter_id']}} </td>
        <td> {{employee['father_name']}} </td>
        <td> {{employee['number']}} </td>
        <td> {{employee['area']}} </td>
        <td> {{employee['salary']}} </td>
        <td> {{employee['manager_name']}} </td>
        <td> {{employee['attendance']}} </td>
        

      </tr>
      {%endfor%}

    </tbody>


  </table>
</div>

  
{%endblock%}