12.office management/application/views/uploader.py
from flask import Blueprint, redirect,render_template,request,flash, url_for
from ..model import db
from bson.objectid import ObjectId

def console(inner):
    print("\n"*3)
    print(inner)
    print("\n"*3)

uploader_blueprint = Blueprint('uploader_blueprint', __name__,static_folder='static',template_folder='template')

@uploader_blueprint.route('/',methods=['POST','GET'])
def uploader():
    if request.method == 'POST':
        form = request.form
        data = dict(form) 
        
        try:
            
            data["area"]
            data["area"] = False
        except:
            data["area"] = True

            
        print(data['area'])
        

        data.update({
        "salary":False,
        "manager_id":"",
        "manager_name":"",
        "attendance":False,
        "area":False 
        })
        
        emp = db['employee'].insert_one(data)
       
        
        db['uploader'].update_one(
            {"_id": ObjectId(   form['uploader_id'] ) },
            
            {'$push':   
                {'uploader_ids':ObjectId(emp.inserted_id)}  
                }
            )
        
        flash(f"{form['name']} \tadded ..")
        return render_template('uploader/index.html')
    
    return render_template('uploader/index.html')




# {
#     "_id": {
#         "$oid": "621fca7930fa3a22b8984329"
#     },
#     "name": "viki",
#     "salary": null,
#     "manager_id": null,
#     "manager_name": null
# }

# @uploader_blueprint.route('/employee_list',methods=['GET','POST'])
# def employee_list():
#     find_query = {}
#     if request.method == 'POST':
#         form = request.form
#         find_query = {'name': {'$regex':  form['name']  }} 
#     return render_template('uploader/employee_list.html',data=[ x for x in  db['employee'].find(find_query)])  

@uploader_blueprint.route('/employee/<_id>')
def employee(_id):
    return render_template('uploader/employee.html',data=db['employee'].find_one({'_id':ObjectId(_id)}))


@uploader_blueprint.route('/my_list/<string:uploader_id>')
def my_list(uploader_id):
    uploader   = db['uploader'].find_one({'_id':ObjectId(uploader_id)})
    find_query = {'_id': {'$in':  uploader['uploader_ids']  }} 

    return render_template('uploader/employee_list.html',data=[ x for x in  db['employee'].find(find_query)])  





@uploader_blueprint.route('/bar_room',methods=['GET','POST'])
def bar_room():
    find_query = {"attendance":False}
    if request.method == 'POST':
        form = request.form
        find_query = {'name': {'$regex':  f'^{form["name"]}', '$options' : 'i'} , "attendance":False} 
        # data = db['employee'].find(find_query)
        
    return render_template("uploader/bar_room.html",data = [ emp for emp in db['employee'].find(find_query) ])



@uploader_blueprint.route('/attendance/<string:_id>')
def attendance(_id):
    print(ObjectId(_id))
    db['employee'].find_one_and_update(
        {"_id":ObjectId(_id)},
        {"$set":{"attendance":True}}
        )
    return redirect(url_for("uploader_blueprint.bar_room"))

12.office management/application/templates/uploader/bar_room.html
{%extends 'layout.html'%}
{%block content%}
{% include 'uploader/navbar.html'%}

<div class="container text-center">

    <div class="d-flex justify-content-center">
        
        <form style="width: 300px;" method="post" action="{{url_for('uploader_blueprint.bar_room')}}">
            <div class="mb-3">
                <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                    placeholder="Employee name" autocomplete="off" name="name">
            </div>
            <input type="text" id="element1" value="{{session.user._id}}" name="uploader_id">

            <button type="submit" class="btn btn-primary ">Search</button>
            <script>
                document.getElementById("element1").style.display = "none";

            </script>
        </form>
    </div>


 
    <div class="">
        <h4 class="m-2">  Result {{data | count}}   </h4>
        
        <table class="table ">
            <thead>
                <tr>
                    <th>Name</th>
                    <th> Voter id</th>
                    <th> Father name</th>
                    <th> Number</th>
                    <th>Outsider</th>
                    <th> Salary</th>
                    <th> Manager_name</th>
                    <th> Attendance</th>
                </tr>
            </thead>
            <tbody>
                {%for employee in data%}
                <tr>
                    <td scope="row">
                        <a href="/uploader/employee/{{employee ._id}}" class="btn">
                            {{employee['name']}}
                        </a>
                    </td>

                    <td> {{employee['voter_id']}} </td>
                    <td> {{employee['father_name']}} </td>
                    <td> {{employee['number']}} </td>
                    <td> {{employee['area']}} </td>
                    <td> {{employee['salary']}} </td>
                    <td> {{employee['manager_name']}} </td>




                    <td scope="row">
                        {%if not employee.attendance %}
                        <a class="btn  btn-outline-danger" href="/uploader/attendance/{{employee._id}}"> Attend </a>
                        {% else %}
                        <span class="h5">attend</span>
                        {%endif%}

                    </td>
                </tr>
                {%endfor%}

            </tbody>

        </table>


    </div>


    {%endblock%}

12.office management/application/templates/uploader/employee.html
{%extends 'layout.html'%}
{%block content%}
{% include 'uploader/navbar.html'%}
<div class="container text-center ">
    <div class="d-flex justify-content-center">
        <h1>{{data['name']}} <span class="text-muted h5"> -  Employee </span></h1>


    </div>

    <div class="d-flex justify-content-center">

        <ul class="list-group " style="width: 600px;">
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Number<span class="h5">{{data['number']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Voter Id<span class="h5">{{data['voter_id']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Father Name<span class="h5">{{data['father_name']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Date of birth<span class="h5">{{data['dob']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Address<span class="h5">{{data['address']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Polling Booth<span class="h5">{{data['polling_booth']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Area<span class="h5">{{data['area']}}</span></li>

        </ul>
    </div>



</div>
{%endblock%}

12.office management/application/templates/uploader/employee_list.html
{%extends 'layout.html'%} {%block content%} {% include 'uploader/navbar.html'%}
<nav class="navbar m-1   members_attendance ">
    <div class="container-fluid">
        <div class="navbar ">
            <h3>Employee {{data | length}} <h3>
        </div>

        <div class="d-flex">
            <ul class="nav nav-pills nav-fill ">


            </ul>


        </div>
    </div>
</nav>

<div class="container">
    <table class="table table-hover">

        <thead>
            <tr>
                <th scope="col">Name</th>

                <th> Voter id</th>
                <th> Father name</th>
                <th> Number</th>
                <th>Outsider</th>
                <th> Salary</th>
                <th> Manager_name</th>
                <th> Attendance</th>

            </tr>
        </thead>



        <tbody>
            {%for employee in data%}
            <tr onclick="window.location='/uploader/employee/{{employee ._id}}' ">
                <th scope="row">{{employee['name']}}</th>
                <td> {{employee['voter_id']}} </td>
                <td> {{employee['father_name']}} </td>
                <td> {{employee['number']}} </td>
                <td> {{employee['area']}} </td>
                <td> {{employee['salary']}} </td>
                <td> {{employee['manager_name']}} </td>
                <td> {{employee['attendance']}} </td>
            </tr>
            {%endfor%}

        </tbody>


    </table>
</div>


{%endblock%}

12.office management/application/templates/uploader/index.html
{%extends 'layout.html'%}

{%block content%}
{% include 'uploader/navbar.html'%}


<div class="container  d-flex justify-content-center">
  <form style="width: 300px;" method="post" action="{{url_for('uploader_blueprint.uploader')}}">
    <!-- <label for="exampleInputEmail1" class="form-label">Employee name</label> -->
    <!-- <div class="mb-3">
        <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Employee name" autocomplete="off"  required name="name">
        </div> -->

    <div class="form-floating m-1 ">
      <input type="text" placeholder=" " name="name" class="form-control " autocomplete="off"  required required>
      <label for="name">Full name</label>
    </div>

    <div class="form-floating m-1">
      <input type="text" placeholder=" " name="voter_id" class="form-control " autocomplete="off"  required >
      <label for="voter_id"> Voter id</label>
    </div>

    <div class="form-floating m-1">
      <input type="text" placeholder=" " name="father_name" class="form-control " autocomplete="off"  required >
      <label for="father_name"> Father Name</label>
    </div>

    <div class="form-floating m-1">
      <input type="date" placeholder=" " name="dob" class="form-control " autocomplete="off"  required >
      <label for="number">Date of Birth</label>
    </div>


    <div class="form-floating m-1">
      <input type="text" placeholder=" " name="address" class="form-control " autocomplete="off"  required >
      <label for="address"> Address</label>
    </div>

    <div class="form-floating m-1">
      <input type="number" placeholder=" " pattern="\d*" maxlength="10" name="number" class="form-control "  autocomplete="off"  required 
        oninput="javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);">
      <label for="number"> Mobile Number</label>
    </div>

    

    <div class="form-check form-check-inline m-2">
      <input class="form-check-input" type="radio" name="area" id="area" >
      <label class="form-check-label" for="area">Outsiders</label>
    </div>



    <div class="form-floating m-1">
      <input type="number" placeholder=" " name="polling_booth" class="form-control " autocomplete="off"  required >
      <label for="polling_booth"> Polling Booth</label>
    </div>




    <input type="text" id="element1" value="{{session.user._id}}" name="uploader_id">
    <button type="submit" class="btn btn-primary m-3">upload</button>
    <script>document.getElementById("element1").style.display = "none";</script>
  </form>


</div>

<div class="container m-3 d-flex justify-content-center">
  {% with messages = get_flashed_messages() %}
  {% if messages %}
  {% for message in messages %}
  <h2>{{ message }}</h2>
  {% endfor %}
  {% endif %}
  {% endwith %}
</div>

{%endblock%}

12.office management/application/templates/uploader/navbar.html
<nav class="navbar m-1   members_attendance ">
  <div class="container-fluid">
    <div class="navbar ">
      <a href="/uploader" class="btn">


        <h3> {{ session.user.name }}

          <small class="h5 text-muted"> - {{session.type}}</small>
        </h3>
      </a>
    </div>

    <div class="d-flex">
      <ul class="nav nav-pills nav-fill ">


        <li class="nav-item  m-2">
          <a class=" btn btn-outline-primary active" aria-current="page"
            href="/uploader/bar_room">Bar room
          </a>
        </li>

        <li class="nav-item  m-2">
          <a class=" btn btn-outline-primary active" aria-current="page"
            href="/uploader/my_list/{{ session.user._id}}">My list
          </a>
        </li>



      </ul>


    </div>
  </div>
</nav>