12.office management/application/views/boss.py
from ..model import db
from flask import Blueprint, redirect,render_template,request, url_for
from bson.objectid import ObjectId

boss_blueprint = Blueprint('boss_blueprint', __name__,static_folder='static',template_folder='template')


def console(inner):
    print("\n"*3)
    print(inner)
    print("\n"*3)


@boss_blueprint.route('/')
def boss():
    manager = db['manager'].count_documents({})
    uploader = db['uploader'].count_documents({})
    employee = db["employee"].count_documents({})
    return render_template('boss/index.html',manager =manager,employee=employee,uploader=uploader)


@boss_blueprint.route('/search_list',methods=['GET','POST'])
def search_list():
    if request.method == 'POST':
        form = request.form
        documents = []
        
        
        regex = {'$regex': f'^{form["search"]}', '$options' : 'i'}  
        
        for type_ in ['manager','employee','uploader']:
            
            for obj in db[type_].find({'name': regex} ):
                documents.append(
                {
                    "documents":obj,
                    "type":type_
                })
        
    return render_template('boss/search_list.html', documents = documents)

@boss_blueprint.route('/search_by_type/<string:by_type>')
def search_by_type(by_type:str):
    return render_template('boss/all_people.html', documents =db[by_type].find(),by_type=by_type,count= db[by_type].count_documents({}) )






# @boss_blueprint.route('/salary')
# def salary():
#     return render_template('boss/salary.html')

@boss_blueprint.route('/manager/<_id>')
def manager(_id):
    manager = db['manager'].find_one({'_id':ObjectId(_id)})
    salary_list = db['employee'].find({    '_id':  { "$in" :manager['salary_list']}      })
    return render_template('boss/manager.html',data=manager,salary_list=salary_list)


@boss_blueprint.route('/update_manager/',methods=["POST"])
def update_manager():
    if request.method == 'POST':
        form = request.form
        
        total_amount = int(form['total_amount']) + int(form['amount'])
        amount = int(form['amount']) + int(form['balance_amount'])
        
        
        db['manager'].find_one_and_update(
            {'_id':ObjectId(form['_id'])},
            {'$set':{'amount':amount , 'total_amount':total_amount } }
            )
    return redirect(url_for('boss_blueprint.manager',_id=form['_id']))
        
    # return render_template('boss/manager.html',data=manager)

@boss_blueprint.route('/employee/<_id>')
def employee(_id):
    return render_template('boss/employee.html',data=db['employee'].find_one({'_id':ObjectId(_id)}) ,by_type = "employee")


@boss_blueprint.route('/uploader/<_id>')
def uploader(_id):
    return render_template('boss/uploader.html',data=db['uploader'].find_one({'_id':ObjectId(_id)}),by_type = "uploader")












def manager_bar_room_list()->list:
    managers = []
    
    for manager in db["manager"].find():
        
        attendance_attend = db["employee"].count_documents( {
            "$and":[
                    {"_id":{"$in":manager['salary_list']}},{"attendance":True}    
                ]
            }),
    
        outsider = db["employee"].count_documents({
            "$and":[{"_id":{"$in":manager['salary_list']}},{"attendance":False},{"area":True}]
            })
    
    
    
        tem = {
            "attendance_attend":attendance_attend[0],        
            "attendance_not_attend": len(manager["salary_list"])-attendance_attend[0],
            "outsider":outsider
        }
        
        
        tem.update(manager)
        managers.append(tem)        
    return managers
    


def main_display()->dict:
    total_employee  = db['employee'].count_documents({})
    attend_total = db['employee'].count_documents({'attendance':True})
    attend_salary = db['employee'].count_documents( {"$and":[{'attendance':True} ,{"salary":True}]} )
    
    balance_total = db['employee'].count_documents({'attendance':False})
    balance_salary = db['employee'].count_documents( {"$and":[{'attendance':False} ,{"salary":True} ]} )
    outsider_salary = db['employee'].count_documents( {"$and":[{'attendance':False} , {"area":True} ,{"salary":True}]} )
    outsider_other = db['employee'].count_documents( {"$and":[{'attendance':False} , {"area":True} ]} )
    
    try:
        winner = attend_salary *100 / attend_total
    except:
        winner = 0
    return {
        "total_employee":total_employee,
        "winner" : round(winner) ,
        
        
        "attend":{
            "total":attend_total,
            "salary":attend_salary,
            "other":attend_total - attend_salary  ,
            },
        "balance":{
            "total":balance_total,
            "salary":balance_salary,
            "other":balance_total - balance_salary,
            "outsider_salary":outsider_salary,
            "outsider_other":outsider_other
            },    
    }
    
    
    
    
    
    

@boss_blueprint.route('/bar_room')
def bar_room():

    return render_template('boss/bar_room.html',     
            display=main_display(),
            manager_list = manager_bar_room_list()
        )

12.office management/application/views/manager.py
from ..model import db
from flask import Blueprint, redirect,render_template,request,session, url_for
from bson.objectid import ObjectId

manager_blueprint = Blueprint('manager_blueprint', __name__,static_folder='static',template_folder='templates')


def console(inner):
    print("\n"*3)
    print(inner)
    print("\n"*3)
    
def return_manager(inner):
    return db['manager'].find_one( {"_id" :ObjectId(inner)} )
    
    
@manager_blueprint.route('/<string:_id>')
def manager(_id):
    return render_template('manager/index.html',manager=return_manager(_id))



    
@manager_blueprint.route('/employee/<string:_id>/<string:manager_id>')
def employee(_id,manager_id):
    
    employee = db['employee'].find_one({'_id':ObjectId(_id)})
    return render_template('manager/employee.html',data=employee,manager = return_manager(manager_id))  


@manager_blueprint.route('/update_manager/',methods=["POST"])
def update_employee():
    if request.method == 'POST':
        form = request.form
        
        manager =  db['manager'].find_one( {"_id" :ObjectId(form['manager_id'])} )
        amount = int(manager["amount"]) - 10
        arr  =  manager['salary_list']
        arr.append(ObjectId(form['employee_id']))
        db['manager'].find_one_and_update(
            {'_id':ObjectId(form['manager_id'])},
            {'$set':{'amount':amount,"salary_list":arr } })

        db['employee'].find_one_and_update(
            {'_id':ObjectId(form['employee_id'])},
            {'$set':{'salary':True ,"manager_name":manager['name'],"manager_id":manager['_id']} })
        
        
    return redirect(url_for('manager_blueprint.employee',_id=ObjectId(form['employee_id']),manager_id=manager["_id"]))




@manager_blueprint.route('/search_list',methods=['GET','POST'])
def search_list():
        if request.method == 'POST':
            form = request.form

        regex = {'$regex':  f'^{form["search"]}', '$options' : 'i'}
        documents = []
        
        for doc in db['employee'].find( {'name': regex} ):
            documents.append(doc)
        
        console(documents)
        
        return render_template('manager/search_list.html',data = {
            "search_list" : documents,
            "search_count" : len(documents)
        },manager=return_manager(form['manager_id']))


@manager_blueprint.route('/salary_list/<string:manager_id>')
def salary_list(manager_id):
    manager  = return_manager(manager_id)
    data = db['employee'].find({    '_id':  { "$in" :manager['salary_list']}      })
    return render_template("manager/salary_list.html",data=data,manager = manager)














@manager_blueprint.route('/bar_room/<string:manager_id>')
def bar_room(manager_id):
    manager  = return_manager(manager_id)

    data = db['employee'].find(
        {"manager_id":ObjectId(manager_id) , "attendance":False}
        )
        
    return render_template("manager/bar_room.html",data = data,manager=manager)

12.office management/application/views/uploader.py
from flask import Blueprint, redirect,render_template,request,flash, url_for
from ..model import db
from bson.objectid import ObjectId

def console(inner):
    print("\n"*3)
    print(inner)
    print("\n"*3)

uploader_blueprint = Blueprint('uploader_blueprint', __name__,static_folder='static',template_folder='template')

@uploader_blueprint.route('/',methods=['POST','GET'])
def uploader():
    if request.method == 'POST':
        form = request.form
        data = dict(form) 
        
        try:
            
            data["area"]
            data["area"] = False
        except:
            data["area"] = True

            
        print(data['area'])
        

        data.update({
        "salary":False,
        "manager_id":"",
        "manager_name":"",
        "attendance":False,
        "area":False 
        })
        
        emp = db['employee'].insert_one(data)
       
        
        db['uploader'].update_one(
            {"_id": ObjectId(   form['uploader_id'] ) },
            
            {'$push':   
                {'uploader_ids':ObjectId(emp.inserted_id)}  
                }
            )
        
        flash(f"{form['name']} \tadded ..")
        return render_template('uploader/index.html')
    
    return render_template('uploader/index.html')




# {
#     "_id": {
#         "$oid": "621fca7930fa3a22b8984329"
#     },
#     "name": "viki",
#     "salary": null,
#     "manager_id": null,
#     "manager_name": null
# }

# @uploader_blueprint.route('/employee_list',methods=['GET','POST'])
# def employee_list():
#     find_query = {}
#     if request.method == 'POST':
#         form = request.form
#         find_query = {'name': {'$regex':  form['name']  }} 
#     return render_template('uploader/employee_list.html',data=[ x for x in  db['employee'].find(find_query)])  

@uploader_blueprint.route('/employee/<_id>')
def employee(_id):
    return render_template('uploader/employee.html',data=db['employee'].find_one({'_id':ObjectId(_id)}))


@uploader_blueprint.route('/my_list/<string:uploader_id>')
def my_list(uploader_id):
    uploader   = db['uploader'].find_one({'_id':ObjectId(uploader_id)})
    find_query = {'_id': {'$in':  uploader['uploader_ids']  }} 

    return render_template('uploader/employee_list.html',data=[ x for x in  db['employee'].find(find_query)])  





@uploader_blueprint.route('/bar_room',methods=['GET','POST'])
def bar_room():
    find_query = {"attendance":False}
    if request.method == 'POST':
        form = request.form
        find_query = {'name': {'$regex':  f'^{form["name"]}', '$options' : 'i'} , "attendance":False} 
        # data = db['employee'].find(find_query)
        
    return render_template("uploader/bar_room.html",data = [ emp for emp in db['employee'].find(find_query) ])



@uploader_blueprint.route('/attendance/<string:_id>')
def attendance(_id):
    print(ObjectId(_id))
    db['employee'].find_one_and_update(
        {"_id":ObjectId(_id)},
        {"$set":{"attendance":True}}
        )
    return redirect(url_for("uploader_blueprint.bar_room"))

12.office management/application/templates/boss/all_people.html
{%extends 'layout.html'%}
{%block content%}
{% include 'boss/navbar.html'%}
<nav class="navbar m-1    " >
    <div class="container-fluid">
    <div class="navbar ">
       <h3> {{by_type | upper}} {{count }}  </h3>
    </div>
      <div class="d-flex">
        <ul class="nav nav-pills nav-fill "  >


        </ul>
        

      </div>
    </div>
  </nav>

<div class="container">
  <table class="table table-hover">

    <thead>
      <tr>
        <th scope="col">Name</th>
        <th >  Voter id</th>
        <th >  Father name</th>
        <th >  Number</th>
        <th >Outsider</th>
        <th >  Salary</th>
        <th >  Manager_name</th>
        <th >  Attendance</th>
        
      </tr>
    </thead>



    <tbody >
      {%for data in documents%}
      <tr onclick="window.location='/boss/{{by_type}}/{{data._id}}' ">
        <th scope="row">{{data.name}}</th>
        <td > {{data.voter_id}} </td>
        <td > {{data.father_name}} </td>
        <td > {{data.number}} </td>
        <td > {{data.area}} </td>
        <td > {{data.salary}} </td>
        <td > {{data.manager_name}} </td>
        <td > {{data.attendance}} </td>
      </tr>
      {%endfor%}

    </tbody>


  </table>
</div>

  
{%endblock%}

12.office management/application/templates/boss/bar_room.html
{%extends 'layout.html'%}
{%block content%}
{% include 'boss/navbar.html'%}
<meta http-equiv="refresh" content="2">
<script src="/static/bar_rom.js"></script>

<div class="container-fluid text-center">


  <div class="row">
  
   
    <div class="col">
      



      <table class="table">
        <thead>
          <tr>
            <th scope="col">Attend</th>
            <th scope="col">Balance</th>
          </tr>
        </thead>
  
        <tbody>
          <tr>
            <td>{{ display['attend']['total'] }} </td>
            <td>
              <h3 class="text-danger">
  
                {{ display['balance']['total']  }}
              </h3>
            </td>
          </tr>
  
          <tr>
            <td>
  
  
              <table class="table">
  
                <thead>
                  <tr>
                    <th scope="col">salary</th>
                    <th scope="col">other</th>
                  </tr>
                </thead>
  
                <tbody>
                  <tr>
                    <td class="text-success h5">{{display['attend']['salary']}} </td>
                    <td>{{display['attend']['other']}}</td>
                  </tr>
  
                </tbody>
              </table>
  
  
            </td>
  
            <td>
              
              <table class="table">
  
                <thead>
                  <tr>
                    <th scope="col">Salary</th>
                    <th scope="col">Other</th>
                    <th scope="col">Outsider</th>
                  </tr>
                </thead>
  
                <tbody>
                  <tr>
                    <td class="text-danger h5"  >{{display['balance']['salary']}}</td>
                    <td>{{display['balance']['other']}}</td>
                    <td > <samp class="text-danger h5">{{display['balance']['outsider_salary']}} </samp>   - {{display['balance']['outsider_other']}} </td>
                  </tr>
  
                </tbody>
              </table>
  
  
  
  
            </td>
            
          </tr>
          <!-- 
            <tr>
            </tr> -->
        </tbody>
      </table>
  







    </div>
    
    
    
    
    
    <div class="col">
      <!-- <h2 id="timer"></h2> -->
      <h2 <small class="h4"> Total employee's </small>  {{display['total_employee']}}</h1>
      <h1 class="text-success"> Winning  {{display['winner']}} % </h1>

    </div>
    
  </div>

 








  <div class="row">
    <!-- <div class="col">
        
      </div> -->







    
    <div class="col">

      <h3>Managers</h3>




      <table class="table table-hover">

        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Number</th>
            <th scope="col">Amount</th>
            <th scope="col">salary given</th>
            <th scope="col">Attend</th>
            <th scope="col">Balance</th>
            <th scope="col">Outsider</th>
          </tr>
        </thead>



        <tbody>
          {%for data in manager_list%}
          <tr onclick="window.location='/boss/manager/{{data._id}}' ">
            <th scope="row">{{data['name']}}</th>
            <th>87654321</th>
            <th>{{data['amount']}} /{{data['total_amount']}}</th>
            <th>{{data['salary_list'] | length}}</th>
            <th>{{data['attendance_attend']}}   </th>
            <th class=" text-danger h4">{{data['attendance_not_attend']}}</th>
            <th>{{data['outsider']}}</th>
          </tr>
          {%endfor%}

        </tbody>


      </table>













    </div>
  </div>
</div>



<style>
  p {
    text-align: center;
    font-size: 25px;
  }

  #timer {

    font-size: 40px;
    font-family: Arial, sans-serif;
    font-weight: bold;

  }
</style>

{%endblock%}

12.office management/application/templates/boss/employee.html
{%extends 'layout.html'%}
{%block content%}
{% include 'boss/navbar.html'%}
<div class="container text-center ">
    <div class="d-flex justify-content-center">
        <h1>{{data['name']}} <span class="text-muted h5"> {{by_type}} </span></h1>


    </div>
    <div class="d-flex justify-content-center">

        <ul class="list-group " style="width: 600px;">
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Number<span class="h5">{{data['number']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Voter Id<span class="h5">{{data['voter_id']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Father Name<span class="h5">{{data['father_name']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Date of birth<span class="h5">{{data['dob']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Address<span class="h5">{{data['address']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Polling Booth<span class="h5">{{data['polling_booth']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Area<span class="h5">{{data['area']}}</span></li>

        </ul>
    </div>
</div>
{%endblock%}

12.office management/application/templates/boss/employee_list.html
{%extends 'layout.html'%}
{%block content%}
{% include 'boss/navbar.html'%}
<nav class="navbar m-1   members_attendance " >
    <div class="container-fluid">
    <div class="navbar ">
       <h3>Employee  {{data['employee_count']}}</h3>
    </div>

      <div class="d-flex">
        <ul class="nav nav-pills nav-fill "  >


        </ul>
        

      </div>
    </div>
  </nav>

<div class="container">
  <table class="table">

    <thead>
      <tr>
        <th scope="col">Name</th>
        <th >  voter_id</th>
        <th >  father_name</th>
        <th >  number</th>
        <th >  salary</th>
        <th >  manager_name</th>
        <th >  attendance</th>
      </tr>
    </thead>



    <tbody>
      {%for data in data['employee_list']%}
      <tr>
        <td scope="row">{{data['name']}}</td>
        <td > {{data['voter_id']}} </td>
        <td > {{data['father_name']}} </td>
        <td > {{data['number']}} </td>
        <td > {{data['salary']}} </td>
        <td > {{data['manager_name']}} </td>
        <td > {{data['attendance']}} </td>
      </tr>
      {%endfor%}

    </tbody>


  </table>
</div>

  
{%endblock%}

12.office management/application/templates/boss/index.html
{%extends 'layout.html'%}
{%block content%}
{% include 'boss/navbar.html'%}


<div class="row row-cols-1 row-cols-md-3 g-4 m-4">
  <div class="col">
    <a class="card m-1 btn " href="/boss/search_by_type/manager">
      <img src="/static/images/manager.webp" class="card-img-top " alt="manager.webp">
      <div class="card-body">
        <h1 >Managers {{manager}}</h1>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional
          content. This content is a little bit longer.</p>
      </div>
    </a>
  </div>
  
  <div class="col">
    <a class="card btn " href="/boss/search_by_type/employee">
      <img src="/static/images/Employees.png" class="card-img-top" alt="Employees.png">
      <div class="card-body">
        <h1 class="card-title ">Employees {{employee}}</h1>

        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional
          content. This content is a little bit longer.</p>
      </div>
    </a>
  </div>
  <div class="col">
    <a class="card btn" href="/boss/search_by_type/uploader">
      <img src="/static/images/uploaders.jpg" class="card-img-top m-1" alt="uploaders.jpg">
      <div class="card-body">
        <h1 class="card-title " >Uploaders {{uploader}}</h1>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional
          content.</p>
      </div>
    </a>
  </div>

</div>
{%endblock%}

12.office management/application/templates/boss/manager.html
{%extends 'layout.html'%} {%block content%} {% include 'boss/navbar.html'%}

<div class="container text-center P-3 ">
    <h2 class="">{{ data['name']}}

        <small>Manager</small>
    </h2>
    <div class="row">

        <div class="col">

            <div class="card">
                <div class="card-header">
                    <h1>{{data['amount']}}</h1>
                    <small>Balance amount</small>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{data['total_amount']}} <small>Total amount</small></h3>

                    <p class="card-text">salary given <b> {{ (data['salary_list'] | length)*10 }} </b>for <b> {{
                            data['salary_list'] | length }} </b> employees </p>

                </div>
            </div>
        </div>

        <div class="col">


            <form style="width: 300px;" method="post" action="{{url_for('boss_blueprint.update_manager')}}">
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Amount</label>
                    <input type="number" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                        autocomplete="off" name="amount">
                </div>
                <input type="text" id="element" name="_id" value="{{data['_id']}}">
                <input type="text" id="element2" name="total_amount" value="{{data['total_amount']}}">
                <input type="text" id="element3" name="balance_amount" value="{{data['amount']}}">


                <button type="submit" class="btn btn-primary m-3">Submit</button>
            </form>

            <script>
                document.getElementById("element").style.display = "none";
                document.getElementById("element2").style.display = "none";
                document.getElementById("element3").style.display = "none";
            </script>
        </div>
    </div>

    <div class="row m-3 ">
        <h2>Salary given Employee list </h2>
        <table class="table">
            <thead>

                <tr>
                    <th scope="col">Name</th>
                    <th ">Attendance</th>
                    <th ">Outsider</th>
                </tr>

            </thead>

            <tbody>
                {%for employee in salary_list %}
                <tr>
                    <th scope="row">{{employee['name']}}</th>
                    <th scope="row">{{employee['attendance']}}</th>
                    <th scope="row">{{employee['area']}}</th>
                </tr>
                {%endfor%}
            </tbody>
        </table>
    </div>

</div>

{%endblock%}

12.office management/application/templates/boss/manager_list.html
{%extends 'layout.html'%} {%block content%} {% include 'boss/navbar.html'%}
<nav class="navbar m-1   members_attendance ">
    <div class="container-fluid">
        <div class="navbar ">
            <h3>Manager {{data['manager_count']}}</h3>
        </div>

        <div class="d-flex">
            <ul class="nav nav-pills nav-fill ">


            </ul>


        </div>
    </div>
</nav>

<div class="container">
    <table class="table table-hover">

        <thead>
            <tr>
                <th scope="col">Name</th>
            </tr>
        </thead>



        <tbody>
            {%for data in data['manager_list']%}
            <tr onclick="window.location='/boss/manager/{{data._id}}' ">
                <th scope="row">{{data['name']}}</th>
            </tr>
            {%endfor%}

        </tbody>


    </table>
</div>


{%endblock%}

12.office management/application/templates/boss/navbar.html
<nav class="navbar    bg-light">
    <div class="container-fluid">

        <div class="navbar ">
            <a href="/boss" class="btn">
                <h4> {{session.user.name }} <small class="h5 text-muted"> - {{session.type}}</small> </h4>
            </a>
        </div>

        <div class="d-flex">
            <ul class="nav nav-pills nav-fill  ">

                <li class="nav-item  m-2">
                    <a class=" btn btn-outline-primary active" aria-current="page"
                        href="{{url_for('boss_blueprint.bar_room')}}">Bar room
                    </a>
                </li>

                <li class="nav-item  m-2">
                    <a class=" btn btn-outline-primary active" aria-current="page"
                        href="/boss/search_by_type/employee">Employee
                    </a>
                </li>

                <li class="nav-item  m-2">
                    <a class=" btn btn-outline-primary active" aria-current="page"
                        href="/boss/search_by_type/manager">Manager
                    </a>
                </li>

                <li class="nav-item  m-2">
                    <a class=" btn btn-outline-primary active" aria-current="page"
                        href="/boss/search_by_type/uploader">Uploader
                    </a>
                </li>



                <li class="nav-item  m-2">
                    <form class="d-flex" method="post" action="{{url_for('boss_blueprint.search_list')}}">
                        <input class="form-control me-2" type="text" aria-label="Search" placeholder="Name" value=""
                            name="search" autocomplete="off">
                        <button type="submit" class="btn btn-primary">Search </button>
                    </form>
                </li>


            </ul>


        </div>
    </div>
</nav>

12.office management/application/templates/boss/salary.html
{%extends 'layout.html'%}
{%block content%}
{% include 'boss/navbar.html'%}

  
{%endblock%}

12.office management/application/templates/boss/search_list.html
{%extends 'layout.html'%}
{%block content%}
{% include 'boss/navbar.html'%}
<nav class="navbar m-1   members_attendance " >
    <div class="container-fluid">
    <div class="navbar ">
       <h3>Search  {{documents | length}}</h3>
    </div>

      <div class="d-flex">
        <ul class="nav nav-pills nav-fill "  >


        </ul>
        

      </div>
    </div>
  </nav>

<div class="container">
  <table class="table table-hover">

    <thead>
      <tr>
        <th scope="col">Name</th>
        <th >  Type</th>

      </tr>
    </thead>



    <tbody>
      {%for data in documents%}
      <tr onclick="window.location='/boss/{{data.type}}/{{data.documents._id}}' ">
        <th scope="row">{{data.documents.name}}</th>
        <th scope="row">{{data.type}}</th>

      </tr>
      {%endfor%}

    </tbody>


  </table>
</div>

  
{%endblock%}

12.office management/application/templates/boss/uploader.html
{%extends 'layout.html'%}
{%block content%}
{% include 'boss/navbar.html'%}
<div class="container text-center ">
    <div class="d-flex justify-content-center">
        <h1>{{data['name']}} <span class="text-muted h5"> {{by_type}} </span></h1>


    </div>
    <div class="d-flex justify-content-center">

        <ul class="list-group " style="width: 400px;">
            <li class="list-group-item d-flex justify-content-between align-items-center">A list item<span class="h5">14</span>
            </li>

        </ul>
    </div>
</div>
{%endblock%}

12.office management/application/templates/boss/uploader_list.html
{%extends 'layout.html'%}
{%block content%}
{% include 'boss/navbar.html'%}
<nav class="navbar m-1   members_attendance " >
    <div class="container-fluid">
    <div class="navbar ">
       <h3>Uploader  {{data['uploader_count']}}</h3>
    </div>

      <div class="d-flex">
        <ul class="nav nav-pills nav-fill "  >


        </ul>
        

      </div>
    </div>
  </nav>

<div class="container">
  <table class="table">

    <thead>
      <tr>
        <th scope="col">Name</th>
      </tr>
    </thead>



    <tbody>
      {%for data in data['uploader_list']%}
      <tr>
        <th scope="row">{{data['name']}}</th>
      </tr>
      {%endfor%}

    </tbody>


  </table>
</div>

  
{%endblock%}