12.office management/application/views/informer.py
from application.views.boss import employee
from ..model import db
from flask import Blueprint, redirect,render_template,request,session, url_for
from bson.objectid import ObjectId

informer_blueprint = Blueprint('informer_blueprint', __name__,static_folder='static',template_folder='templates')

@informer_blueprint.route("/",methods=['GET','POST'])
def employee_list():
    employee =[]
    
    if request.method == 'POST':        
        form = request.form
        if not form["search"] == "" :
            regex = {'$regex': f'^{form["search"]}', '$options' : 'i'}  
            employee =db["employee"].find({'name': regex} )
        
    return render_template("informer/index.html",employee_list= employee)



@informer_blueprint.route('/employee/<string:_id>')
def employee(_id):
    employee = db['employee'].find_one({'_id':ObjectId(_id)})
    return render_template('informer/employee.html',data=employee)  

12.office management/application/templates/informer/employee.html
{%extends 'layout.html'%}
{%block content%}

<div class="container text-center ">
    <div class="d-flex justify-content-center">
        <h1>{{data['name']}} <span class="text-muted h5"> {{by_type}} </span></h1>


    </div>
    
    <div class="d-flex justify-content-center">

        <ul class="list-group " style="width: 400px;">
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Voter Id<span class="h5">{{data['voter_id']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Father Name<span class="h5">{{data['father_name']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Date of birth<span class="h5">{{data['dob']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Address<span class="h5">{{data['address']}}</span></li>
            <li class="list-group-item d-flex justify-content-between align-items-center m-1">Polling Booth<span class="h5">{{data['polling_booth']}}</span></li>

        </ul>
    </div>



</div>




{%endblock%}

12.office management/application/templates/informer/index.html
{%extends 'layout.html'%}
{%block content%}



<div class="container text-center">

    <div class="d-flex justify-content-center m-4">
        
        <form style="width: 300px;" method="post" action="{{url_for('informer_blueprint.employee_list')}}">
            <div class="mb-3">
                <input type="text" class="form-control" placeholder="Employee name" autocomplete="off" name="search">
            </div>

            <button type="submit" class="btn btn-primary ">Search</button>

        </form>
    </div>


 
    <div class="">
        <h4 class="m-2">  Result   </h4>
        
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th> Voter id</th>
                    <th> Father name</th>
                    <th> Date of birth</th>
                    <th>Polling Booth Number</th>
                    

                </tr>
            </thead>
            <tbody>
                {%for employee in employee_list%}
                <tr onclick="window.location='/informer/employee/{{employee._id}}' ">


                    <td> {{employee['name']}} </td>
                    <td> {{employee['voter_id']}} </td>
                    <td> {{employee['father_name']}} </td>
                    <td> {{employee['dob']}} </td>
                    <td> {{employee['polling_booth']}} </td>





                </tr>
                {%endfor%}

            </tbody>

        </table>


    </div>


{%endblock%}